# Generated by Django 4.1.1 on 2022-10-03 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_member_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fboard',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=1000)),
                ('b_content', models.TextField()),
                ('b_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 21, 40, 50, 55144))),
                ('b_group', models.IntegerField(default=0)),
                ('b_step', models.IntegerField(default=0)),
                ('b_indent', models.IntegerField(default=0)),
                ('b_hit', models.IntegerField(default=1)),
                ('b_file', models.ImageField(blank=True, upload_to='')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
