# Generated by Django 4.1.1 on 2022-10-10 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_reg_date'),
        ('freeBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 2, 26, 16, 513506)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('c_pw', models.CharField(blank=True, max_length=10)),
                ('c_content', models.TextField()),
                ('c_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 2, 26, 16, 513506))),
                ('fboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeBoard.fboard')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
