# Generated by Django 4.1.1 on 2022-10-20 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeBoard', '0003_revenue_alter_comment_c_date_alter_fboard_b_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 17, 5, 40, 367585)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 17, 5, 40, 366585)),
        ),
    ]
