# Generated by Django 4.1.1 on 2022-10-01 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
                ('birth', models.DateField(blank=True)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=200)),
                ('hobby', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 17, 4, 28, 924671))),
            ],
        ),
    ]
