# Generated by Django 4.1.1 on 2022-10-03 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 21, 40, 50, 53168)),
        ),
    ]
